services:
    # Magento
    magento:
        image: ghcr.io/erikngigi/magento:latest
        hostname: magento
        container_name: magento
        restart: unless-stopped
        tty: true
        volumes:
          - ./src/magento/php:/home/magento/php:cached
          - ./src/magento/magento2:/home/magento/magento2:cached
          - ./templates/php/php/info.php:/home/magento/php/info.php
          - ./templates/php/php/magento/php.ini-development:/usr/local/etc/php/php.ini:ro
          - ./templates/php/php-fpm.d/magento/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
          - ./templates/php/php-fpm.d/magento/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
        ports:
          - "9000:9000"
        networks:
          - akeneo-magento-app-network
    # Akeneo
    akeneo:
        image: ghcr.io/erikngigi/akeneo:latest
        hostname: akeneo
        container_name: akeneo
        restart: unless-stopped
        tty: true
        volumes:
          - ./src/akeneo/php:/home/akeneo/php:cached
          - ./src/akeneo/akeneo7:/home/akeneo/akeneo7:cached
          - ./templates/php/php/info.php:/home/akeneo/php/info.php
          - ./templates/php/php/akeneo/php.ini-development:/usr/local/etc/php/php.ini:ro
          - ./templates/php/php-fpm.d/akeneo/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
          - ./templates/php/php-fpm.d/akeneo/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
        ports:
          - "9050:9050"
        networks:
          - akeneo-magento-app-network
        depends_on:
          - "mysql-db"
    # MySQL
    mysql-db:
        image: mysql:8.4
        hostname: mysql-db
        container_name: mysql-db
        restart: unless-stopped
        tty: true
        ports:
          - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        networks:
          - akeneo-magento-app-network
        volumes:
          - db-data:/var/lib/mysql/
          - ./templates/mysql:/docker-entrypoint-initdb.d
          - ./templates/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    # Elastisearch
    elasticsearch:
        image: elasticsearch:8.19.19
        hostname: elasticsearch
        container_name: elasticsearch
        ports:
          - "9100:9200"
        networks:
          - akeneo-magento-app-network
        volumes:
          - ./templates/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
          - ./templates/elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options.d/jvm.options
          - es-data:/usr/share/elasticsearch/data
        depends_on:
          - akeneo
          - magento
networks:
    akeneo-magento-app-network:
        name: akeneo-magento-app-network
        driver: bridge
volumes:
    es-data:
        name: elasticsearch-data-volume
        driver: local
    db-data:
        name: mysql-database-volume
        driver: local
