services:
  # Magento
  magento:
    image: ghcr.io/erikngigi/magento:latest
    hostname: magento
    container_name: magento
    restart: unless-stopped
    tty: true
    volumes:
      # Application Source Code Bind Mount
      - ./src/magento:/home/appuser/magento2:cached

      # Health/Info Diagnostic Tools
      - ./magento/templates/diagnostics/info.php:/home/appuser/tools/info.php:ro

      # Configuration Files
      - ./magento/settings/php/php.ini-development:/usr/local/etc/php/php.ini:ro
      - ./magento/settings/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./magento/settings/php-fpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
    ports:
      - "9000:9000"
    networks:
      - ecommerce-network

  # Magento MariaDB Database
  magento-db:
    image: mariadb:11.4
    hostname: magento-db
    container_name: magento-db
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MAGENTO_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MAGENTO_DATABASE}
      MYSQL_USER: ${MAGENTO_USER}
      MYSQL_PASSWORD: ${MAGENTO_DB_USER_PASSWORD}
    networks:
      - ecommerce-network
    volumes:
      - magento-db-data:/var/lib/mysql

  # Magento OpenSearch Engine
  magento-opensearch:
    image: opensearchproject/opensearch:2.11.0
    hostname: magento-opensearch
    container_name: magento-opensearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - "9250:9200"
    networks:
      - ecommerce-network
    volumes:
      - magento-opensearch-data:/usr/share/opensearch/data


  # Akeneo
  akeneo:
    image: ghcr.io/erikngigi/akeneo:latest
    hostname: akeneo
    container_name: akeneo
    restart: unless-stopped
    tty: true
    volumes:
      # Application Source Code Bind Mount
      - ./src/akeneo:/home/appuser/akeneo7:cached

      # Health/Info Diagnostic Tools
      - ./akeneo/templates/diagnostics/info.php:/home/appuser/tools/info.php:ro

      # Configuration Files
      - ./akeneo/settings/php/php.ini-development:/usr/local/etc/php/php.ini:ro
      - ./akeneo/settings/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./akeneo/settings/php-fpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
    ports:
      - "9050:9050"
    networks:
      - ecommerce-network
    depends_on:
      - akeneo-db

  # Akeneo MySQL Database
  akeneo-db:
    image: mysql:8.0.30
    hostname: akeneo-db
    container_name: akeneo-db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${AKENEO_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${AKENEO_DATABASE}
      MYSQL_USER: ${AKENEO_USER}
      MYSQL_PASSWORD: ${AKENEO_DB_USER_PASSWORD}
    networks:
      - ecommerce-network
    volumes:
      - akeneo-db-data:/var/lib/mysql/
      - ./mysql/settings/my.cnf:/etc/mysql/conf.d/my.cnf:ro

  # Akeneo Elastisearch Engine
  elasticsearch:
    image: elasticsearch:8.4.2
    hostname: akeneo-es
    container_name: akeneo-es
    ports:
      - "9100:9200"
    networks:
      - ecommerce-network
    volumes:
      - ./elasticsearch/settings/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/settings/jvm.options:/usr/share/elasticsearch/config/jvm.options.d/jvm.options
      - akeneo-es-data:/usr/share/elasticsearch/data
    depends_on:
      - akeneo-db


networks:
  ecommerce-network:
    name: ecommerce-network
    driver: bridge
volumes:
  akeneo-db-data:
    name: akeneo-mysql-db
    driver: local
  akeneo-es-data:
    name: akeneo-elasticsearch-volume
    driver: local
  magento-db-data:
    name: magento-mariadb-volume
    driver: local
  magento-opensearch-data:
    name: magento-opensearch-volume
    driver: local
