# Upstream blocks for backend services
upstream fastcgi_backend {
 server 127.0.0.1:9000;
}

# Server block for Magento

server {
 listen 80;
 server_name magento.ericngigi.com;
 return 301 https://$host$request_uri;
}

server {
  listen 443 ssl http2;
  server_name magento.ericngigi.com;

  set $MAGE_ROOT /home/eric/ecommerce-stack-docker/src/magento/magento2;
  include /home/eric/ecommerce-stack-docker/src/magento/magento2/nginx.conf.sample;
  client_max_body_size 25m;

  access_log /var/log/nginx/magento.ericngigi.access.log;
  error_log  /var/log/nginx/magento.ericngigi.error.log;

  # TLS configuration
  ssl_certificate /etc/letsencrypt/live/magento.ericngigi.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/magento.ericngigi.com/privkey.pem;
  ssl_protocols TLSv1.2 TLSv1.3;

  ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384';
  ssl_prefer_server_ciphers on;
  ssl_session_cache shared:SSL:50m;
  ssl_session_timeout 1d;

  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_pass fastcgi_backend;
    fastcgi_param SCRIPT_FILENAME /home/magento/magento2/pub$fastcgi_script_name;
    fastcgi_param HTTP_AUTHORIZATION $http_authorization;
    fastcgi_intercept_errors on;
  }

  # PHP-FPM Status Page
  location = /status {
    access_log off;
    allow 127.0.0.1;
    allow 105.163.157.96;
    deny all;

    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $fastcgi_script_name;
    fastcgi_pass fastcgi_backend;
  }

  location = /info.php {
    access_log off;
    allow 127.0.0.1;
    allow 105.163.157.96;
    deny all;

    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME /home/eric/ecommerce-stack-docker/src/magento/php$fastcgi_script_name;
    fastcgi_pass fastcgi_backend;
  }
}
