# Upstream blocks for backend services
upstream akeneo_backend {
    server 127.0.0.1:9050;
}

# Server block for Akeneo
server {
    listen 80;
    server_name akeneo.ericngigi.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name akeneo.ericngigi.com;

    root /home/eric/ecommerce-stack-docker/src/akeneo/public;
    index index.php;
    client_max_body_size 25m;

    access_log /var/log/nginx/akeneo.ericngigi.access.log;
    error_log /var/log/nginx/akeneo.ericngigi.error.log;

    # TLS configuration
    ssl_certificate /etc/letsencrypt/live/akeneo.ericngigi.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/akeneo.ericngigi.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384';
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:50m;
    ssl_session_timeout 1d;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass akeneo_backend;
        fastcgi_param SCRIPT_FILENAME /home/appuser/akeneo7/public$fastcgi_script_name;
        fastcgi_param HTTP_AUTHORIZATION $http_authorization;
        fastcgi_intercept_errors on;
    }

    location /bundles {
        autoindex off;
    }

    # PHP-FPM Status Page
    location = /status {
        access_log off;
        allow 127.0.0.1;
        allow 105.163.157.96;
        deny all;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $fastcgi_script_name;
        fastcgi_pass akeneo_backend;
    }

    # PHP-FPM Health Ping Page
    location = /ping {
        access_log off;
        allow 127.0.0.1;
        allow 105.163.157.96;
        deny all;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $fastcgi_script_name;
        fastcgi_pass akeneo_backend;
    }

    location = /info.php {
        access_log off;
        allow 127.0.0.1;
        allow 105.163.157.96;
        deny all;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /home/appuser/tools$fastcgi_script_name;
        fastcgi_pass akeneo_backend;
    }
}
